### ISSUE TITLE
Wordpress 4.1/WC 2.3.5 compatibility

### ISSUE THREAD

**Issue by wintherd** [yuloh/woocommerce-phone-payments#1] opened 2015-04-22 22:37 UTC
I am having some issues with the plugin. With a created order (including order items) - after calculating totals and saving the order, the "Add Payment" button changes to a message "Please calculate totals and save before adding a payment."  The Add Payment button never returns for the order.  Any ideas?

**Comment by matt-allan** [comment] 2015-10-03 19:01
Hello,

You should only see the "Please calculate totals and save before adding a payment" message if the order total is not set or $0.00.

You can see the code [here](https://github.com/matthew-james/woocommerce-phone-payments/blob/master/woocommerce-phone-payments.php#L36) that determines whether or not to show that message.  Not sure why the order total would be empty.

I was unable to reproduce this on a fresh install of WC 2.4.7 and WP 4.3.1, so I am going to close this as could not reproduce.

**Closed as completed** 2015-10-03 19:07 UTC
